### ISSUE TITLE
Is it possible make autosearch protocol for binding with noname toy?

### ISSUE THREAD

**Issue by samodergec** [pascallanger/DIY-Multiprotocol-TX-Module#209]
A lot of toys from China uses standard protocol but we don't know which one. Is it possible for autosearch required protocol based on the seccefull binding with toy?

**Comment by pascallanger** [comment]
It looks hard to achieve:
 - not all protocols are working the same way which makes it difficult to automate something
 - the module has no way to know if a protocol is accepted or not since most protocols are unidirectional
 - there is no obvious way to notify which current protocol is being tested
 - some toys even if using a different protocol still reacts to other protocols so they need to have a reset between the trials
 - ...
