### ISSUE TITLE
PPM mode + TAER radio + FrSky D8 receiver

### ISSUE THREAD

**Issue by Shkolik** [pascallanger/DIY-Multiprotocol-TX-Module#233]
Hi! I have 2 modules running the same FW but 1 working in serial mode in my Jumper t12, second integrated in my Spektrum dx6i (PPM). Both TX's outputs in TAER order and I define it in config.
Today I found that FrSky  D8 compatible receiver work fine with Jumper, but with dx6i chanel order wrong. 
With FlySky receivers everithing work ok, and I asumed that it's protocol bug. 
I modified frsky2way_data_frame() function to pass **CH_AETR[i]** instead **i** into **convert_channel_frsky**

I dont know if it's right, but it helps.

BTW, I dont know if FrSky default chanel order is AETR, maybe it's just my mistake and I need to remap chanels on my jumper and use another pads on receiver.

PS: Receiver I used: [https://www.banggood.com/2_4G-8CH-D8-Mini-FrSky-Compatibel-Receiver-With-PWM-PPM-SBUS-Output-p-1140478.html](url)

**Comment by pascallanger** [comment]
FrSky does not have any default mapping like other protocols. This is why you just have "i" and not any mapping.
I'm not sure both TX really output the same since otherwise the module would output the same. The module doesn't know the channel order it just takes the input channels and use them for ouput.
