### ISSUE TITLE
Disabeling the configuration if OrangeTX to PPM incorrect

### ISSUE THREAD

**Issue by OpenUAS** [pascallanger/DIY-Multiprotocol-TX-Module#247]
In validate.h there is written:

```
...
//Change/Force configuration if OrangeTX
#ifdef ORANGE_TX
	#undef ENABLE_PPM			// Disable PPM for OrangeTX module
...
```

Should this not be
`#undef ENABLE_SERIAL		// Disable SERIAL for OrangeTX module`

This module only has a PPM input AFAIK. Just to be very sure, defining ORANGE_TX we talk about this module containing a Blue or Green PCB right?

![OrangeRx_module_for_in_TX](https://user-images.githubusercontent.com/483944/61970228-9f318780-afdc-11e9-83ec-fb4076d0c273.jpg)

**Comment by pascallanger** [comment]
This is the right module.
Serial is working for sure so validate.h is correct.
I'm not sure about PPM, this needs to be tested as I don't have a module. Are you willing to give it a go?
Pascal

**Comment by pascallanger** [comment]
In fact I remember now, PPM is disabled/untested since there is no hardware way to select which protocol is being launched.
So if you really want to use it with PPM you also need to force the bank and the correct ppm entry in the table and test to see if it works.
Serial gives you access to any of the CYRF protocols along with all the options which is how it has been developped as a goal.

**Comment by OpenUAS** [comment]
Did not know it had serial, will test PPM mode then Hava blue and green version...

**Comment by OpenUAS** [comment]
Move to own issue queue of Fork as not to pollute this tracker to much. When fixed and tested and all works 100% a new PR will be created.
