### ISSUE TITLE
Any plans for FASST?

### ISSUE THREAD

**Issue by azaitsev** [pascallanger/DIY-Multiprotocol-TX-Module#357]
Hi guys, awesome project. I'm surprised you haven't yet implemented FASST support. Have you any feature plans for that?

**Comment by pascallanger** [comment]
If you are talking about Futaba FASST, I don't think it can be supported since they are using a special RF chip.
But I can have a look to see if it's doable to emulate it from another component. For these I would need someone to ship me a TX and RX. If you are willing to do it then say so otherwise I can only close your request.

**Comment by azaitsev** [comment]
I have only one radio so I can't ship it. I can make photos of components inside or record an rf sample with hackrf.

**Comment by pascallanger** [comment]
That won't help. Tons of data is needed to reverse a protocol. So I guess this is a dead end at least for now.
