### ISSUE TITLE
BUGS 3 MULTIPROTOCOL

### ISSUE THREAD

**Issue by TheMagno** [pascallanger/DIY-Multiprotocol-TX-Module#446]
HI
I have a Radiomaster TX16S and also a Jumper 4IN1 module, I can bind with any of them and Bugs 3, but the only thing I can do with any of them is arm the engines!  I have AETR properly configured and even the LEDs work on channel 10! Bugs 3 works with the original command!

**Comment by pascallanger** [comment]
I think you should post on the forum instead of here so people with the same model can help.
All I can say is that this protocol has been tested by multiple people successfully and has not been touched for a long time. So my guess is that it's more your setup. So the basic questions would apply like: are you sure you have checked the channel monitor and Throttle is moving as it should on the output? no trim applied on throttle, throttle set to -100/+100%,...
