### ISSUE TITLE
FlySky sensor FS-CAT01 use for vario

### ISSUE THREAD

**Issue by franz4949** [pascallanger/DIY-Multiprotocol-TX-Module#624]
With my RM-TX16S I have bound an FS-iA6B receiver with connected altitude sensor FS-CAT01. Telemetry data of sensor are found and seem to work properly. I wished to use this Rx/sensor combination for a glider, so I configured the vario with the altitude as source but I cannot get it working properly. Altitude value in quiet air (indoor) is jumping between +0.1m and -0.6m, altitude value is set to 2 decimal digits. Manual lifting/lowering doesn't change vario tone (as I am used to hear from e.g. FrSky vario).

I don*t know whether the vario unsuitability comes from sensor hardware limitations, from Rx firmware or from MPM sensor teölemetry data handling. Help and/or improvement for vario signal use would be highly appreciated. The way vario with this sensor works now is completely unsuitable for thermal soaring.

**Comment by pascallanger** [comment]
As you can see from [the manufacturer page](https://www.flysky-cn.com/cat01-canshu), there is no accuracy given on the altitude. There is also no statement of any vario. Therefore my conclusion is that you only have a high range (0-8000m) lower sensitivity sensor in the fs-cat01. The vario air pressure sensor is usually in addition of an altitude air pressure sensor since you need to know the altitude and temperature to correct the high sensitivity vario values. If a vario is available you usually have a m/s sensor which I don't think you have in this case. Using just the altitude value will end up with what you describe.

**Comment by franz4949** [comment]
Hi Jim, I think this is not the right place for your intended project. The better place would be here => https://github.com/openXsensor/openXsensor
I believe if you could make the openXsensor work with the FlySky iBus, many pilots would appreciate that and make use of it.
